// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';

const SUPABASE_URL = "https://zubqolwowzomspiupggr.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inp1YnFvbHdvd3pvbXNwaXVwZ2dyIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjQ4Njk4ODMsImV4cCI6MjA4MDQ0NTg4M30.R0HZZ2kq5aj6OlgX74_DPOMu-uz1Stdd083_l_5a9yo";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);